version: '3'
services:
  jupyterlab:
    image: ericonyame/jupyterlab-postgres:latest
    env_file: .env
    ports:
      - "8890:8888"
    volumes:
      - ./:/problem5
    networks:
      - dbnetwork
  postgres:
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork

networks:
  dbnetwork:
   

volumes:
  postgresdata:
