version: '3'
services:
  jupyterlab:
    image: ericonyame/jupyterlab-postgres:latest
    env_file: .env
    ports:
      - "8890:8888"
    volumes:
      - ./problem5:/problem5
    networks:
      - dbnetwork
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: mydatabase
    volumes:
      - postgresdata:/var/lib/postgresql/data
    networks:
      - dbnetwork

networks:
  dbnetwork:
    driver: bridge

volumes:
  postgresdata:
